server {
    listen 80;
    server_name supabase-prd-serapod.getouch.my;
    root /usr/share/nginx/html;
    index supabase.html;

    location / {
        try_files /supabase.html =404;
    }
}

server {
    listen 80;
    server_name wa.getouch.my;
    root /usr/share/nginx/html;
    index evolution-api.html;

    location / {
        try_files /evolution-api.html =404;
    }
}

server {
    listen 80;
    server_name chat.getouch.my;
    root /usr/share/nginx/html;
    index open-webui.html;

    location / {
        try_files /open-webui.html =404;
    }
}