---
- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: medium
      hourCycle: h23

- resources:
    label: Host
    cpu: true
    memory: true
    uptime: true
    refresh: 3000

- resources:
    label: Disk
    disk: /
    refresh: 10000
